
# NOTE: these tests exercise the DEPRECATED class-template record (`TemplateRecord`) — fields
# declared as class attributes and cloned per instance. Kept to cover that behaviour; new code
# should use `CompositeRecord` with an explicit `__init__`. See spire/composite/record.py.
from spire.composite.record import TemplateRecord
from spire.composite.array import Array
from spire.expr import SInt, UInt, Wire, Signal


from spire.expr import (
    UInt,
    Wire,
    Signal,
    Input,
    Output,
    Register,
    Expr,
    Const,
    reset_shared_cache,
    Slice,
    HDLType,
)
from spire.component import Netlist
from spire.simulator import Simulator


def test_composite_record_basic():
    class MyRecord(TemplateRecord):
        a = Wire(UInt(8))
        b = Wire(SInt(4))
        c = Array([Wire(UInt(8)) for _ in range(4)])

    b0 = MyRecord()
    b1 = MyRecord()

    # b0.a and b1.a are distinct Wire instances with same typ
    assert b0.a is not b1.a
    assert b0.a.typ.width == 8

    # Type inference:
    b0 <<= b1  # inferred return type: MyRecord (via HDLComposite.__ilshift__)


# -------------------------------------------------------------------
# Test records used below
# -------------------------------------------------------------------


class MyRecord(TemplateRecord):
    a = Wire(UInt(8))
    b = Wire(UInt(4))


class RecordWithArray(TemplateRecord):
    a   = Wire(UInt(8))
    vec = Array([Wire(UInt(2)) for _ in range(3)])  # 3×2 bits


# -------------------------------------------------------------------
# Tests
# -------------------------------------------------------------------


def test_compositerecord_instance_clones_wires():
    reset_shared_cache()

    b0 = MyRecord()
    b1 = MyRecord()

    # Each instance must have its own wires
    assert isinstance(b0.a, Signal)
    assert isinstance(b0.b, Signal)
    assert isinstance(b1.a, Signal)
    assert isinstance(b1.b, Signal)

    assert b0.a is not b1.a
    assert b0.b is not b1.b

    # Types preserved
    assert b0.a.typ.width == 8
    assert b0.b.typ.width == 4
    assert b0.a.kind == "wire"
    assert b0.b.kind == "wire"


def test_compositerecord_templates_collected():
    # Class-level fields are captured as per-class templates. They also remain class attributes,
    # which is what gives IDE autocomplete on the field names.
    tmpl = MyRecord._record_field_templates
    assert set(tmpl.keys()) == {"a", "b"}
    assert tmpl["a"].kind == "wire" and tmpl["a"].typ.width == 8
    assert tmpl["b"].kind == "wire" and tmpl["b"].typ.width == 4


def test_compositerecord_override_field_in_ctor():
    reset_shared_cache()

    custom_a = Wire(UInt(8))
    b = MyRecord(a=custom_a)

    # 'a' is the override; 'b' is still auto-cloned (distinct from the class template).
    assert b.a is custom_a
    assert isinstance(b.b, Signal)
    assert b.b is not MyRecord._record_field_templates["b"]


def test_compositerecord_unknown_kwarg_adds_field():
    # Lenient: an undeclared kwarg adds a field rather than raising.
    reset_shared_cache()

    extra = Wire(UInt(3))
    b = MyRecord(x=extra)

    assert b.x is extra
    # The new field participates in flattening / width (a=8, b=4, x=3 -> 15).
    assert b.width == 8 + 4 + 3


def test_compositerecord_clone_preserves_kind():
    # Templates may carry any direction/kind (not wire-only); clones preserve it and take the
    # field-key as the port name.
    reset_shared_cache()

    class Bundle(TemplateRecord):
        i = Input(UInt(8))
        o = Output(UInt(4))
        r = Register(UInt(2))

    b0 = Bundle()
    b1 = Bundle()

    assert b0.i.kind == "input"
    assert b0.o.kind == "output"
    assert b0.r.kind == "reg"
    assert b0.i is not b1.i              # cloned per instance
    assert b0.i.name == "i" and b0.o.name == "o" and b0.r.name == "r"


def test_compositerecord_to_bits_and_width():
    reset_shared_cache()

    b = MyRecord()
    bits = b.to_bits()

    # Width = 8 + 4 = 12
    assert bits.typ.width == 12
    assert b.width == 12

    # to_bits must be an Expr
    assert isinstance(bits, Expr)


def test_compositerecord_assign_from_bits_slices_correctly():
    reset_shared_cache()

    b = MyRecord()

    # Total width 12 bits, use a constant with that width
    val = 0xABC  # 0b1010_1011_1100 (just something nontrivial)
    bits = Const(val, HDLType(12, signed=False, is_bool=False))

    # Structural assignment via HDLComposite API
    b.assign(bits)

    # a: first 8 bits (LSB side)
    # b: next 4 bits
    assert isinstance(b.a, Signal)
    assert isinstance(b.b, Signal)
    assert b.a._driver._auto_generated # autogenerated signal, look one level deeper
    assert isinstance(b.a._driver._driver, Slice)
    assert b.b._driver._auto_generated # autogenerated signal, look one level deeper
    assert isinstance(b.b._driver._driver, Slice)

    # a gets bits[0:8]
    assert b.a._driver._driver.lsb == 0
    assert b.a._driver._driver.msb == 7

    # b gets bits[8:12]
    assert b.b._driver._driver.lsb == 8
    assert b.b._driver._driver.msb == 11


def test_compositerecord_elementwise_assign_from_other_record():
    reset_shared_cache()

    src = MyRecord()
    dst = MyRecord()

    # For clarity, drive src.a/src.b with constants
    src.a <<= Const(0x12, UInt(8))
    src.b <<= Const(0x3, UInt(4))

    # Element-wise assignment (<<=) uses field-wise semantics
    dst @= src

    assert isinstance(dst.a._driver, Signal)
    assert isinstance(dst.b._driver, Signal)

    # dst.a driven by src.a; dst.b driven by src.b
    assert dst.a._driver is src.a
    assert dst.b._driver is src.b


def test_compositerecord_with_nested_array_clone_and_width():
    reset_shared_cache()

    b0 = RecordWithArray()
    b1 = RecordWithArray()

    # a: 8 bits, vec: 3×2 bits → total width = 8 + 6 = 14
    assert b0.width == 14
    assert b1.width == 14

    # vec must be an Array, and elements must be distinct wires per instance
    assert isinstance(b0.vec, Array)
    assert isinstance(b1.vec, Array)

    assert len(b0.vec) == 3
    assert len(b1.vec) == 3

    for e0, e1 in zip(b0.vec, b1.vec):
        assert isinstance(e0, Signal)
        assert isinstance(e1, Signal)
        assert e0 is not e1
        assert e0.kind == "wire"
        assert e0.typ.width == 2

    bits0 = b0.to_bits()
    bits1 = b1.to_bits()
    assert bits0.typ.width == 14
    assert bits1.typ.width == 14


def test_compositerecord_with_nested_array_assign_from_bits():
    reset_shared_cache()

    b = RecordWithArray()

    # 8 + 3×2 = 14 bits
    val = 0x2A3F  # any value; lower 14 bits used
    bits = Const(val, HDLType(14, signed=False, is_bool=False))

    # Packed structural assignment into the record
    b.assign(bits)

    # a is 8 bits → should get the lowest 8 bits of val
    expected_a = val & ((1 << 8) - 1)
    assert _eval_expr(b.a) == expected_a

    # vec elements each 2 bits, in order:
    #   v0: bits[9:8], v1: bits[11:10], v2: bits[13:12]
    for idx, elem in enumerate(b.vec):
        expected_elem = (val >> (8 + 2 * idx)) & 0b11
        assert _eval_expr(elem) == expected_elem
        
# Small helper: evaluate an Expr to an integer using the simulator
def _eval_expr(e: Expr) -> int:
    m = Netlist("FPTest", with_clock=False, with_reset=False)
    sim = Simulator(m)
    return sim.peek(e)


# -------------------------------------------------------------------
# Signal <-> Composite assignment (BitSerializableLike: a composite is packed to a single
# bitvector when it drives a signal, and sliced back across leaves in reverse).
# MyRecord packs as: a = bits[0:8] (LSBs), b = bits[8:12].
# -------------------------------------------------------------------


def test_signal_assigned_from_composite_packs_bits():
    # signal <<= composite : the composite is packed via to_bits() into the signal's driver.
    reset_shared_cache()
    rec = MyRecord()
    rec.a <<= Const(0x5A, UInt(8))
    rec.b <<= Const(0xC, UInt(4))

    w = Wire(UInt(12))
    w <<= rec

    assert w._driver.typ.width == 12          # packed to the composite's total width
    assert _eval_expr(w) == 0xC5A             # (b << 8) | a == (0xC << 8) | 0x5A


def test_signal_assigned_from_composite_width_fits():
    # A wider target zero-extends: fit_width is applied after to_bits().
    reset_shared_cache()
    rec = MyRecord()
    rec.a <<= Const(0x5A, UInt(8))
    rec.b <<= Const(0xC, UInt(4))

    w = Wire(UInt(16))
    w <<= rec

    assert w._driver.typ.width == 16
    assert _eval_expr(w) == 0xC5A             # high 4 bits zero-extended


def test_composite_assigned_from_signal_unpacks_bits():
    # composite <<= signal : the scalar bitvector is sliced across the composite's leaves.
    reset_shared_cache()
    src = Wire(UInt(12))
    src <<= Const(0xC5A, UInt(12))

    dst = MyRecord()
    dst <<= src

    assert _eval_expr(dst.a) == 0x5A          # bits[0:8]
    assert _eval_expr(dst.b) == 0xC           # bits[8:12]


def test_signal_composite_signal_roundtrip():
    # signal -> composite -> signal preserves the bit pattern.
    reset_shared_cache()
    src = Wire(UInt(12))
    src <<= Const(0xABC, UInt(12))

    mid = MyRecord()
    mid <<= src                               # unpack into the record's leaves
    out = Wire(UInt(12))
    out <<= mid                               # repack the record into a scalar

    assert _eval_expr(out) == 0xABC


if __name__ == "__main__":
    test_composite_record_basic()
    test_compositerecord_instance_clones_wires()
    test_compositerecord_templates_collected()
    test_compositerecord_override_field_in_ctor()
    test_compositerecord_unknown_kwarg_adds_field()
    test_compositerecord_clone_preserves_kind()
    test_compositerecord_to_bits_and_width()
    test_compositerecord_assign_from_bits_slices_correctly()
    test_compositerecord_elementwise_assign_from_other_record()
    test_compositerecord_with_nested_array_clone_and_width()
    test_compositerecord_with_nested_array_assign_from_bits()
    test_signal_assigned_from_composite_packs_bits()
    test_signal_assigned_from_composite_width_fits()
    test_composite_assigned_from_signal_unpacks_bits()
    test_signal_composite_signal_roundtrip()
