"""Netlist -> Lean 4 circuit model, Lake project scaffolding, `lake build` and the proof checker.

Roles in a slot's Lean project (only SpireSemantics.lean is handwritten; it ships with this package):
    Interface.lean          Inputs / Outputs, generated from the port list
    GoldenCircuit.lean      the golden's `eval`, generated from its netlist at registration
    Spec.lean               canonical target `Correct e := ∀ i, e i = GoldenCircuit.eval i`; never changes
    specs/<Name>.lean       optional authored spec layers, each admitted with `<Name>.equiv : ∀ e, <Name>.Correct e ↔ Spec.Correct e`
    D<hash>_Circuit.lean    a design's `eval`, generated from its netlist
    D<hash>_Proof.lean      the submitted proof: `implements : Spec.Correct D<hash>_Circuit.eval` (may import layers and other designs)
The package never writes a proof; it translates, assembles, builds and audits.
"""
from __future__ import annotations
import re
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Iterable, List, Mapping, Optional, Sequence, Set, Tuple

from spire.expr import Concat, Const, Expr, Op1, Op2, Resize, Signal, Slice, Ternary
from spire.visitor import ExprVisitor, expr_children

LEAN_TOOLCHAIN = 'leanprover/lean4:v4.33.1'
SEMANTICS_MODULE = 'SpireSemantics'
SEMANTICS_FILE = Path(__file__).with_name(f'{SEMANTICS_MODULE}.lean')

# (width, signed) per port name
Interface = Dict[str, Tuple[int, bool]]


def lean_ident(name: str) -> str:
    s = ''.join(c if (c.isalnum() or c == '_') else '_' for c in name)
    if not s or s[0].isdigit(): s = 'n_' + s
    if s in {'def', 'theorem', 'match', 'if', 'then', 'else', 'where', 'let', 'in', 'structure', 'namespace', 'end'}:
        s += '_'
    return s


def lean_type_comment(width: int, signed: bool) -> str:
    return f"BitVec {width}  -- Spire {'SInt' if signed else 'UInt'}"


class InterfaceMismatch(ValueError):
    """The netlist's ports do not match the interface it is checked against."""


Port = Dict[str, object]          # {"name", "width", "signed", "dir"} — the design_db port_spec format


def netlist_ports(netlist) -> List[Port]:
    return [{"name": p.name, "width": p.typ.width, "signed": bool(getattr(p.typ, "signed", False)), "dir": p.kind}
            for p in netlist._ports if p.kind in ("input", "output")]


def interface_to_lean(ports: Sequence[Port], *, module: str = 'Interface') -> str:
    def fields(d):
        return [f"  {lean_ident(p['name'])} : {lean_type_comment(p['width'], p['signed'])}" for p in ports if p['dir'] == d]
    return '\n'.join([f'-- GENERATED by spire.design_db.lean.bridge.interface_to_lean from the slot port list; do not edit.',
                       f'namespace {module}', '', 'structure Inputs where', *fields('input'), '',
                       '@[ext] structure Outputs where', *fields('output'), '', f'end {module}', ''])


RESERVED_MODULES = {SEMANTICS_MODULE, 'Interface', 'Spec', 'GoldenCircuit'}
FINAL_THEOREM = 'implements'


def default_spec_lean(*, interface_module: str = 'Interface', golden_module: str = 'GoldenCircuit') -> str:
    """The canonical target of every Lean slot: equal to the golden on every input. Never changes."""
    return f"""-- GENERATED at freeze; the slot's canonical spec. Never edited: every stored proof targets it.
import {interface_module}
import {golden_module}
open {interface_module}
namespace Spec
def Correct (eval : Inputs → Outputs) : Prop := ∀ i, eval i = {golden_module}.eval i
end Spec
"""


def design_modules(hash10: str) -> Tuple[str, str]:
    """(circuit module, proof module) of a design, from its structural-hash prefix."""
    return f'D{hash10}_Circuit', f'D{hash10}_Proof'


def lean_imports(text: str) -> List[str]:
    return [m.group(1) for m in re.finditer(r'^import\s+(\S+)', text, re.M)]


@dataclass(frozen=True)
class LeanExportOptions:
    namespace: str                                # e.g. CandidateCircuit
    interface_module: str = 'Interface'           # module defining Inputs / Outputs
    source_name: str = ''                         # netlist name, for the header comment
    semantics_import: str = SEMANTICS_MODULE
    ports: Optional[Sequence[Port]] = None        # if given, the netlist must match exactly


class _Visitor(ExprVisitor[str]):
    def __init__(self, input_names: Dict[int, str]):
        super().__init__(); self.input_names = input_names
    def visit_const(self, e: Const) -> str:
        return f"BitVec.ofInt {e.typ.width} ({e.value})" if e.typ.signed else f"BitVec.ofNat {e.typ.width} {e.value}"
    def visit_signal(self, e: Signal) -> str:
        if e.kind == 'input': return f"i.{self.input_names[id(e)]}"
        if e.kind == 'reg': raise NotImplementedError('registers not supported')
        if e._driver is None: raise ValueError(f'undriven signal {e.name}')
        return self.visit(e._driver)        # reinterpret wire: BitVec holds the pattern only
    def visit_op1(self, e): raise NotImplementedError(f'op1 {e.op}')
    def visit_op2(self, e: Op2) -> str:
        a, b = self.visit(e.a), self.visit(e.b); wo = e.typ.width
        if e.op in ('*', '+') and e.a.typ.signed and e.b.typ.signed and e.typ.signed:
            return f"{'mulSS' if e.op == '*' else 'addSS'} {wo} ({a}) ({b})"
        raise NotImplementedError(f"unsupported op {e.op} {e.a.typ.width}{'s' if e.a.typ.signed else 'u'} x "
                                  f"{e.b.typ.width}{'s' if e.b.typ.signed else 'u'} -> {e.typ.width}{'s' if e.typ.signed else 'u'}")
    def visit_ternary(self, e): raise NotImplementedError('mux')
    def visit_concat(self, e): raise NotImplementedError('concat')
    def visit_slice(self, e): raise NotImplementedError('slice')
    def visit_resize(self, e: Resize) -> str:
        return f"{'resizeS' if e.a.typ.signed else 'resizeU'} {e.typ.width} ({self.visit(e.a)})"
    def visit_array_index(self, e): raise NotImplementedError('memory')


def collect_signed_arith_shapes(netlist) -> Set[Tuple[str, int, int, int]]:
    netlist.collect_signals(); seen = set(); shapes = set()
    def walk(e):
        if e is None or id(e) in seen: return
        seen.add(id(e))
        if isinstance(e, Op2) and e.op in ('+', '*') and e.a.typ.signed and e.b.typ.signed and e.typ.signed:
            shapes.add((e.op, e.a.typ.width, e.b.typ.width, e.typ.width))
        for c in expr_children(e): walk(c)
    for p in netlist._ports:
        if p.kind == 'output': walk(p)
    return shapes


def _check_ports(have: Sequence[Port], want: Sequence[Port]):
    key = lambda p: (p['dir'], lean_ident(p['name']))
    h = {key(p): (p['width'], bool(p['signed'])) for p in have}; w = {key(p): (p['width'], bool(p['signed'])) for p in want}
    if h == w: return
    diff = [f"  {d} {n}: netlist={h.get((d, n))} interface={w.get((d, n))}" for (d, n) in sorted(set(h) | set(w)) if h.get((d, n)) != w.get((d, n))]
    raise InterfaceMismatch('netlist ports do not match the interface:\n' + '\n'.join(diff))


def _reject_custom_verilog(netlist):
    """The Lean model is built from the elaborated netlist; a component that emits its own Verilog
    would make design.v and the proven model disagree, so it is refused."""
    owners = [getattr(netlist, 'component', None)] + [getattr(s, '_owning_component', None) for s in netlist._signals]
    for c in owners:
        if c is not None and hasattr(c, 'custom_verilog'):
            raise NotImplementedError(f'{type(c).__name__} provides custom_verilog(); not admissible to a Lean-gated slot')


def netlist_to_lean(netlist, *, options: LeanExportOptions) -> str:
    """Emit `<namespace>.eval : Inputs -> Outputs`; the types come from options.interface_module."""
    netlist.collect_signals()
    if any(s.kind in ('reg', 'mem') for s in netlist._signals):
        raise NotImplementedError('combinational-only')
    _reject_custom_verilog(netlist)
    if options.ports is not None: _check_ports(netlist_ports(netlist), options.ports)
    inputs = [p for p in netlist._ports if p.kind == 'input']; outputs = [p for p in netlist._ports if p.kind == 'output']
    v = _Visitor({id(p): lean_ident(p.name) for p in inputs})
    body = [f"    {lean_ident(p.name)} := {v.visit(p)}{',' if ix + 1 < len(outputs) else ''}" for ix, p in enumerate(outputs)]
    return '\n'.join([f"-- GENERATED by spire.design_db.lean.bridge from the lowered Spire netlist '{options.source_name or options.namespace}'; do not edit.",
                       f'import {options.semantics_import}', f'import {options.interface_module}', '',
                       f'open {options.semantics_import} {options.interface_module}', '',
                       f'namespace {options.namespace}', '', 'def eval (i : Inputs) : Outputs :=', '  {', *body, '  }', '',
                       f'end {options.namespace}', ''])


def netlist_to_lean_file(netlist, path, *, options): Path(path).write_text(netlist_to_lean(netlist, options=options))


# --------------------------------------------------------------------------------------
# Lake project scaffolding
# --------------------------------------------------------------------------------------

class LakeNotFoundError(RuntimeError):
    """`lake` is not on PATH, so generated proofs cannot be checked."""


class LeanBuildError(RuntimeError):
    """`lake build` (or a check file) reported errors."""


class ProofCheckError(RuntimeError):
    """A proof compiled but does not establish the spec, or relies on disallowed axioms."""


def write_lean_project(lean_dir: Path, roots: Iterable[str], *,
                       package: str = 'spireAutoLeanMatmul',
                       lib: str = 'SpireAutoLeanMatmul') -> Dict[str, Path]:
    """Write lakefile.lean, lean-toolchain and a copy of SpireSemantics.lean into lean_dir."""
    lean_dir = Path(lean_dir); lean_dir.mkdir(parents=True, exist_ok=True)
    all_roots = [SEMANTICS_MODULE] + [r for r in roots if r != SEMANTICS_MODULE]
    sem = lean_dir / f'{SEMANTICS_MODULE}.lean'
    sem.write_text(SEMANTICS_FILE.read_text())
    root_lines = ',\n'.join(f'    `{r}' for r in all_roots)
    lakefile = lean_dir / 'lakefile.lean'
    lakefile.write_text(
        '-- Generated by spire.design_db.lean.bridge.write_lean_project; do not edit.\n'
        'import Lake\nopen Lake DSL\n\n'
        f'package «{package}» where\n\n'
        '@[default_target]\n'
        f'lean_lib «{lib}» where\n'
        f'  roots := #[\n{root_lines}\n  ]\n')
    toolchain = lean_dir / 'lean-toolchain'
    toolchain.write_text(LEAN_TOOLCHAIN + '\n')
    return {'semantics': sem, 'lakefile': lakefile, 'toolchain': toolchain}


def find_lake() -> str:
    lake = shutil.which('lake')
    if lake is None:
        raise LakeNotFoundError(
            '`lake` (the Lean 4 build tool) is not on PATH, so the generated proofs cannot be '
            'checked. Install elan (https://github.com/leanprover/elan) and make sure '
            '~/.elan/bin (or $ELAN_HOME/bin) is on PATH.')
    return lake


def lake_build(lean_dir: Path, *targets: str, timeout: float = 900) -> str:
    """Run `lake build [targets]` in lean_dir. Raises LakeNotFoundError / LeanBuildError; returns the log."""
    lake = find_lake()
    proc = subprocess.run([lake, 'build', *targets], cwd=str(lean_dir), capture_output=True, text=True, timeout=timeout)
    log = proc.stdout + proc.stderr
    if proc.returncode != 0:
        raise LeanBuildError(f'lake build failed in {lean_dir} (exit {proc.returncode}):\n{log}')
    return log


# --------------------------------------------------------------------------------------
# Proof checker: the proof file is the only editable one, so after `lake build` we verify
# that its final theorem still has the spec's type and uses only allowed axioms.
# --------------------------------------------------------------------------------------

@dataclass(frozen=True)
class TheoremCheck:
    module: str          # proof module to import, e.g. BalancedMmacProof
    theorem: str         # fully qualified, e.g. BalancedMmacProof.implements_mmac
    expected_type: str   # e.g. MmacSpec.Correct BalancedMmacCircuit.eval


BASE_AXIOMS = {'propext', 'Classical.choice', 'Quot.sound'}
# Statement head of the per-declaration axiom `bv_decide` introduces when it trusts the native LRAT
# checker. Axioms are admitted by their *type*, never by their name: names are author-controlled
# (a forged `axiom x._native.bv_decide.ax_1_1 : False` must be rejected).
BV_DECIDE_CERT_HEAD = 'Std.Tactic.BVDecide.Reflect.verifyBVExpr'

_AX_LINE = re.compile(r'AXIOM (?P<thm>\S+) (?P<name>\S+) \| module=(?P<module>\S+) \| type=(?P<type>.*)$')

# One report per theorem; every line is tagged with the theorem so no block splitting is needed.
_AXIOM_REPORT = (
    "open Lean Meta in\n"
    "run_meta do\n"
    "  let env ← getEnv\n"
    "  let axs ← collectAxioms ``{thm}\n"
    "  for ax in axs do\n"
    "    let modName := match env.getModuleIdxFor? ax with\n"
    "      | some i => toString env.header.moduleNames[i.toNat]!\n"
    "      | none => \"<current file>\"\n"
    "    let ty := (env.find? ax).get!.type\n"
    "    logInfo m!\"AXIOM {thm} {{ax}} | module={{modName}} | type={{ty}}\"\n")


def _allowed_axiom(name: str, module: str, typ: str, check: TheoremCheck) -> bool:
    if name in BASE_AXIOMS: return True
    # bv_decide certificate axioms, identified by statement. Policy on top: not attached to the final
    # theorem itself (no whole-design SAT directly in `implements`; a heuristic, not a soundness rule).
    if typ.startswith(BV_DECIDE_CERT_HEAD):
        return not name.startswith(check.theorem + '.')
    return False


def check_theorems(lean_dir: Path, checks: Sequence[TheoremCheck], *, timeout: float = 300) -> Dict[str, List[str]]:
    """Type-check each theorem against its expected statement and audit its axioms.

    Returns {theorem: [axioms]}. Raises ProofCheckError if a theorem does not have the expected type
    (e.g. the statement was weakened) or depends on sorry / a disallowed axiom. Axioms are judged by
    their *statement* (with their origin module reported), never by their name.
    """
    lake = find_lake()
    L = ['-- GENERATED scratch file; deleted after the check.', 'import Lean']
    L += [f'import {c.module}' for c in checks]
    for c in checks:
        L.append(f'example : {c.expected_type} := {c.theorem}')
        L.append(_AXIOM_REPORT.format(thm=c.theorem))
    scratch = Path(lean_dir) / '_CheckProofs.lean'
    scratch.write_text('\n'.join(L) + '\n')
    try:
        proc = subprocess.run([lake, 'env', 'lean', scratch.name], cwd=str(lean_dir),
                              capture_output=True, text=True, timeout=timeout)
    finally:
        scratch.unlink(missing_ok=True)
    log = proc.stdout + proc.stderr
    if proc.returncode != 0:
        raise ProofCheckError('a proof does not establish its spec statement:\n' + log)
    found: Dict[str, List[Tuple[str, str, str]]] = {c.theorem: [] for c in checks}
    for line in log.splitlines():
        m = _AX_LINE.search(line)
        if m and m.group('thm') in found:
            found[m.group('thm')].append((m.group('name'), m.group('module'), m.group('type').strip()))
    axioms: Dict[str, List[str]] = {}
    for c in checks:
        rep = found[c.theorem]
        if not rep and 'AXIOM' not in log:
            raise ProofCheckError(f'no axiom report for {c.theorem}:\n{log}')
        axioms[c.theorem] = [n for n, _, _ in rep]
        bad = [f'{n} : {t[:50]} (declared in {mod})' for n, mod, t in rep if not _allowed_axiom(n, mod, t, c)]
        if bad:
            raise ProofCheckError(f'{c.theorem} depends on disallowed axioms {bad} '
                                  '(sorry, custom axiom, or SAT on the whole design)')
    return axioms
