"""State Const provenance sentinels (Step 1 of the FSM-encoding-search plan).

Every Const auto-generated by ``State.__init_subclass__`` must carry
``_state_class`` and ``_state_name`` back-pointers so the downstream
walker / encoding-search code can identify state Consts unambiguously
without relying on ``(value, width)`` matching (which would collide with
literal zero, register init values, mask constants, etc.).
"""
from __future__ import annotations

import pytest

from spire.expr import Const, UInt
from spire.state import Encoding, State, state


class Demo(State, encoding=Encoding.BINARY):
    A = state()
    B = state()
    C = state()


class Other(State, encoding=Encoding.ONEHOT):
    X = state()
    Y = state()


def test_state_consts_carry_class_and_name():
    assert Demo.A._state_class is Demo
    assert Demo.A._state_name == "A"
    assert Demo.B._state_class is Demo
    assert Demo.B._state_name == "B"
    assert Demo.C._state_class is Demo
    assert Demo.C._state_name == "C"


def test_state_consts_distinguish_classes():
    """Two unrelated State subclasses must not see each other's Consts."""
    assert Demo.A._state_class is not Other.X._state_class
    assert Other.X._state_class is Other
    assert Other.Y._state_class is Other


def test_plain_const_lacks_sentinels():
    """Literal Consts (not from State) must not carry the sentinel — otherwise
    detection becomes ambiguous again."""
    c = Const(0, UInt(2))
    assert getattr(c, "_state_class", None) is None
    assert getattr(c, "_state_name", None) is None


def test_unambiguous_detection_predicate():
    """The exact predicate the downstream walker will use."""
    def is_state_const(expr, cls):
        return isinstance(expr, Const) and getattr(expr, "_state_class", None) is cls

    assert is_state_const(Demo.A, Demo)
    assert is_state_const(Demo.B, Demo)
    assert not is_state_const(Demo.A, Other)           # cross-class rejection
    assert not is_state_const(Const(0, UInt(2)), Demo) # literal rejection
    assert not is_state_const(Const(1, UInt(3)), Other)


def test_state_const_value_matches_declared_encoding():
    """Sentinel addition must not break the original Const value contract."""
    assert Demo.A.value == 0
    assert Demo.B.value == 1
    assert Demo.C.value == 2
    assert Other.X.value == 0b01
    assert Other.Y.value == 0b10


def test_state_const_is_a_genuine_const():
    """Sentinels are extra attributes only — the object is still a Const."""
    assert isinstance(Demo.A, Const)
    assert Demo.A.typ.width == 2
