import sys as _sys

# SpireHDL's expr-graph walkers (e.g. _SignalCollector during to_verilog) recurse one frame per node down driver/expression chains.
# Wide datapaths (deep adder/mux trees) exceed CPython's default 1000-frame limit.
# This is just a patch and not fixing the root cause. For this walkers should be rewritten to be iterative instead of recursive.
if _sys.getrecursionlimit() < 200000:
    _sys.setrecursionlimit(200000)

VERILOG_BANNER = "// Generated by SpireHDL — https://github.com/huawei-csl/spire-hdl"

# ---------------------------------------------------------------------------
# Public API. `Component` is the one abstraction users author; IO is declared with
# `IORecord` + `Input`/`Output`; `Simulator` runs a Component or a Netlist. The flat
# netlist IR (`Netlist`, formerly `Module`) is intentionally NOT exported here — power
# users import it from `spire.ir`. VERILOG_BANNER is defined above so the modules
# imported below (which do `from spire import VERILOG_BANNER`) resolve cleanly.
# ---------------------------------------------------------------------------
from spire.expr import Bool, SInt, UInt, Signal, Wire, Register, Input, Output  # noqa: E402
from spire.io_record import IORecord  # noqa: E402
from spire.component import Component, ImportedComponent  # noqa: E402
from spire.simulator import Simulator  # noqa: E402

__all__ = [
    "Component", "ImportedComponent",
    "IORecord", "Input", "Output",
    "Signal", "Wire", "Register",
    "Bool", "UInt", "SInt",
    "Simulator",
    "VERILOG_BANNER",
]
