import sys as _sys

# Spire's expr-graph walkers (e.g. _SignalCollector during to_verilog) recurse one frame per node down driver/expression chains.
# Wide datapaths (deep adder/mux trees) exceed CPython's default 1000-frame limit.
# This is just a patch and not fixing the root cause. For this walkers should be rewritten to be iterative instead of recursive.
if _sys.getrecursionlimit() < 200000:
    _sys.setrecursionlimit(200000)

VERILOG_BANNER = "// Generated by Spire HDL — https://github.com/huawei-csl/spire-hdl"

# ---------------------------------------------------------------------------
# Public API. `Component` is the one abstraction users author; IO is declared with
# `IORecord` + `Input`/`Output`; `Simulator` runs a Component or a Netlist. The flat
# netlist IR (`Netlist`) is intentionally NOT exported here — power
# users import it from `spire.ir`. VERILOG_BANNER is defined above so the modules
# imported below (which do `from spire import VERILOG_BANNER`) resolve cleanly.
# ---------------------------------------------------------------------------
from spire.expr import Bool, SInt, UInt, Signal, Wire, Register, Input, Output  # noqa: E402
from spire.io_record import IORecord, Flipped, connect  # noqa: E402
from spire.component import Component, CustomVerilogComponent, ImportedComponent  # noqa: E402
from spire.simulator import Simulator  # noqa: E402
from spire.selection_emission import (  # noqa: E402
    SelectionEmissionConfig, selection_topology)
from spire import reduce  # noqa: E402  # submodule: spire.reduce.max_(...) etc.

__all__ = [
    "Component", "CustomVerilogComponent", "ImportedComponent",
    "IORecord", "Input", "Output", "Flipped", "connect",
    "Signal", "Wire", "Register",
    "Bool", "UInt", "SInt",
    "Simulator",
    "SelectionEmissionConfig", "selection_topology",
    "reduce",
    "VERILOG_BANNER",
]

# Runtime version: resolved from installed metadata; falls back for src checkouts.
try:
    from importlib.metadata import version as _pkg_version
    __version__ = _pkg_version("spire-hdl")
except Exception:  # pragma: no cover - not installed (editable/src usage)
    __version__ = "0.0.0+unknown"
