from __future__ import annotations

import inspect
import linecache
import re
from typing import Any, Optional

_VALID_VERILOG_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_$]*$")

# IEEE 1364-2005 reserved words, plus the SystemVerilog ones tools hit when reading with -sv.
VERILOG_KEYWORDS = frozenset("""
always and assign automatic begin buf bufif0 bufif1 case casex casez cell cmos config deassign default defparam
design disable edge else end endcase endconfig endfunction endgenerate endmodule endprimitive endspecify endtable
endtask event for force forever fork function generate genvar highz0 highz1 if ifnone incdir include initial inout
input instance integer join large liblist library localparam macromodule medium module nand negedge nmos nor
noshowcancelled not notif0 notif1 or output parameter pmos posedge primitive pull0 pull1 pulldown pullup
pulsestyle_onevent pulsestyle_ondetect rcmos real realtime reg release repeat rnmos rpmos rtran rtranif0 rtranif1
scalared showcancelled signed small specify specparam strong0 strong1 supply0 supply1 table task time tran tranif0
tranif1 tri tri0 tri1 triand trior trireg unsigned use uwire vectored wait wand weak0 weak1 while wire wor xnor xor
logic bit byte int shortint longint always_comb always_ff always_latch enum struct union typedef unique priority
packed interface modport var void return break continue do final
""".split())


def is_legal_verilog_identifier(name: str) -> bool:
    return bool(_VALID_VERILOG_IDENT_RE.match(name)) and name not in VERILOG_KEYWORDS
# Matches `x = Signal(...)` / `x = Wire(...)` / `x = Register(...)` / `x = Input(...)` / `x = Output(...)`
# (including the keyword-argument form used in IO bundles, e.g. `a = Input(...)`). One regex covers all of
# them since Wire/Register/Input/Output are Signal subclasses that route their name inference through Signal.
_ASSIGN_SIGNAL_RE = re.compile(
    r"^\s*(?:self\.)?(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*(?::[^=]+)?=\s*(?:Signal|Wire|Register|Input|Output)\s*\("
)
_ASSIGN_MEM_RE = re.compile(
    r"^\s*(?:self\.)?(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*(?::[^=]+)?=\s*_MemoryArray\s*\("
)
_ASSIGN_EXPR_RE = re.compile(
    r"^\s*(?:self\.)?(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*(?::[^=]+)?=\s*(?!=)"
)


def sanitize_signal_name(name: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_$]", "_", name)
    if not cleaned:
        return ""
    if cleaned[0].isdigit():
        cleaned = f"sig_{cleaned}"
    if cleaned in VERILOG_KEYWORDS:
        cleaned = f"{cleaned}_"
    if not _VALID_VERILOG_IDENT_RE.match(cleaned):
        return ""
    return cleaned


def infer_signal_name_from_assignment(default_prefix: str, assign_kind: str, this_file: str) -> str:
    """
    Best-effort name inference for ``x = Wire(...)`` / ``x = Register(...)`` /
    ``x = _MemoryArray(...)``. Falls back to a stable autogenerated name when source
    inspection is unavailable.
    """
    assign_re = _ASSIGN_MEM_RE if assign_kind == "mem" else _ASSIGN_SIGNAL_RE

    frame = inspect.currentframe()
    caller = frame.f_back if frame is not None else None
    skip_files = {this_file, __file__}
    while caller is not None and caller.f_code.co_filename in skip_files:
        caller = caller.f_back

    if caller is not None:
        src_line = linecache.getline(caller.f_code.co_filename, caller.f_lineno)
        if src_line:
            m = assign_re.match(src_line)
            if m:
                inferred = sanitize_signal_name(m.group("name"))
                if inferred:
                    return inferred
    # Autogenerated fallback. Draw from `_SharedCache.index` so it resets/snapshots with sig_N (cache determinism).
    from spire.expr import _SharedCache
    idx = _SharedCache.index
    _SharedCache.index += 1
    if caller is not None:
        return f"{default_prefix}_{caller.f_lineno}_{idx}"
    return f"{default_prefix}_{idx}"


def infer_expression_binding_name(this_file: str) -> Optional[str]:
    """
    Best-effort variable-name inference for expressions, e.g.:
      sum = a + b
    """
    frame = inspect.currentframe()
    caller = frame.f_back if frame is not None else None
    skip_files = {this_file, __file__}
    while caller is not None and caller.f_code.co_filename in skip_files:
        caller = caller.f_back

    if caller is None:
        return None

    src_line = linecache.getline(caller.f_code.co_filename, caller.f_lineno)
    if not src_line:
        return None
    if "<<=" in src_line:
        return None

    m = _ASSIGN_EXPR_RE.match(src_line)
    if not m:
        return None
    name = sanitize_signal_name(m.group("name"))
    return name or None


def mark_expr_name(expr: Any, this_file: str) -> Any:
    suggested = infer_expression_binding_name(this_file)
    if suggested:
        expr._suggested_name = suggested
    return expr


def resolve_shared_wire_name(
    suggested_name: Optional[str],
    used_names: set[str],
    index: int,
) -> tuple[str, int]:
    if suggested_name:
        base = sanitize_signal_name(suggested_name)
        if base:
            name = base
            suffix = 0
            while name in used_names:
                suffix += 1
                name = f"{base}_{suffix}"
            return name, index

    return f"sig_{index}", index + 1
