import sys as _sys

# SpireHDL's expr-graph walkers (e.g. _SignalCollector during to_verilog) recurse one frame per node down driver/expression chains.
# Wide datapaths (deep adder/mux trees) exceed CPython's default 1000-frame limit.
# This is just a patch and not fixing the root cause. For this walkers should be rewritten to be iterative instead of recursive.
if _sys.getrecursionlimit() < 200000:
    _sys.setrecursionlimit(200000)

VERILOG_BANNER = "// Generated by SpireHDL — https://github.com/huawei-csl/spire-hdl"
